services:
  app:
    env_file:
      .env
    build: .
    image: redwonder/jailgas-rails
    container_name: rails
    ports:
      - '3000:3000'
    volumes:
      - ./log/app:/var/www/jailgas/log
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'jailgas'
      MYSQL_USER: 'jailgas'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
volumes:
  mysql: