version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: rails-docker
    container_name: rails
    volumes:
      - ./log/app:/var/www/jailgas/log
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: rails-nginx
    container_name: nginx
    volumes:
      - ./log/web:/var/www/jailgas/log
    ports:
      - "80:80"
    depends_on:
      - app

