# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.where([{ name:  'Star Wars' }, { name:  'Lord of the Rings' }])
#   Character.where(name:  'Luke', movie: movies.first)


Config.where(product_name: '10kg').first_or_create(product_name: '10kg', cost: 0, count: 0)
Config.where(product_name: '20kg').first_or_create(product_name: '20kg', cost: 0, count: 0)
Config.where(product_name: '50kg').first_or_create(product_name: '50kg', cost: 0, count: 0)
Config.where(product_name: 'air').first_or_create(product_name: 'air', cost: 0, count: 0)
Config.where(product_name: 'butane').first_or_create(product_name: 'butane', cost: 0, count: 0)
Config.where(product_name: 'argon').first_or_create(product_name: 'argon', cost: 0, count: 0)
Config.where(product_name: 'share').first_or_create(product_name: 'share', cost: 0, count: 0)
Config.where(product_name: 'per_money').first_or_create(product_name: 'per_money', cost: 0, count: 0)

Resident.where(dong: 'A', ho: 101, name: '최화출').first_or_create(dong: 'A', ho: 101, name: '최화출', active: 1)
Resident.where(dong: 'A', ho: 102, name: '최화출').first_or_create(dong: 'A', ho: 102, name: '최화출', active: 1)
Resident.where(dong: 'A', ho: 103, name: '최인섭').first_or_create(dong: 'A', ho: 103, name: '최인섭', active: 1)
Resident.where(dong: 'A', ho: 104, name: '최광섭').first_or_create(dong: 'A', ho: 104, name: '최광섭', active: 1)
Resident.where(dong: 'A', ho: 105, name: '김미옥(2)').first_or_create(dong: 'A', ho: 105, name: '김미옥(2)', active: 1)
Resident.where(dong: 'A', ho: 106, name: '김두수').first_or_create(dong: 'A', ho: 106, name: '김두수', active: 1)
Resident.where(dong: 'A', ho: 107, name: '김지수(2)').first_or_create(dong: 'A', ho: 107, name: '김지수(2)', active: 1)
Resident.where(dong: 'A', ho: 201, name: '최병천').first_or_create(dong: 'A', ho: 201, name: '최병천', active: 1)
Resident.where(dong: 'A', ho: 202, name: '김부길').first_or_create(dong: 'A', ho: 202, name: '김부길', active: 1)
Resident.where(dong: 'A', ho: 203, name: '최병택').first_or_create(dong: 'A', ho: 203, name: '최병택', active: 1)
Resident.where(dong: 'A', ho: 204, name: '곽희진(2)').first_or_create(dong: 'A', ho: 204, name: '곽희진(2)', active: 1)
Resident.where(dong: 'A', ho: 205, name: '김병기').first_or_create(dong: 'A', ho: 205, name: '김병기', active: 1)
Resident.where(dong: 'A', ho: 206, name: '김기술').first_or_create(dong: 'A', ho: 206, name: '김기술', active: 1)
Resident.where(dong: 'A', ho: 207, name: '곽 휘').first_or_create(dong: 'A', ho: 207, name: '곽 휘', active: 1)
Resident.where(dong: 'A', ho: 208, name: '정례분').first_or_create(dong: 'A', ho: 208, name: '정례분', active: 1)

Resident.where(dong: 'B', ho: 101, name: '최언섭').first_or_create(dong: 'B', ho: 101, name: '최언섭', active: 1)
Resident.where(dong: 'B', ho: 102, name: '신경옥').first_or_create(dong: 'B', ho: 102, name: '신경옥', active: 1)
Resident.where(dong: 'B', ho: 103, name: '최경섭(2)').first_or_create(dong: 'B', ho: 103, name: '최경섭(2)', active: 1)
Resident.where(dong: 'B', ho: 104, name: '김동웅').first_or_create(dong: 'B', ho: 104, name: '김동웅', active: 1)
Resident.where(dong: 'B', ho: 105, name: '이태언').first_or_create(dong: 'B', ho: 105, name: '이태언', active: 1)
Resident.where(dong: 'B', ho: 106, name: '염달선(1.5)').first_or_create(dong: 'B', ho: 106, name: '염달선(1.5)', active: 1)
Resident.where(dong: 'B', ho: 107, name: '최득섭(1.5)').first_or_create(dong: 'B', ho: 107, name: '최득섭(1.5)', active: 1)
Resident.where(dong: 'B', ho: 201, name: '최순출').first_or_create(dong: 'B', ho: 201, name: '최순출', active: 1)
Resident.where(dong: 'B', ho: 202, name: '김명희').first_or_create(dong: 'B', ho: 202, name: '김명희', active: 1)
Resident.where(dong: 'B', ho: 203, name: '김의호').first_or_create(dong: 'B', ho: 203, name: '김의호', active: 1)
Resident.where(dong: 'B', ho: 204, name: '황순예').first_or_create(dong: 'B', ho: 204, name: '황순예', active: 1)
Resident.where(dong: 'B', ho: 205, name: '최권섭').first_or_create(dong: 'B', ho: 205, name: '최권섭', active: 1)
Resident.where(dong: 'B', ho: 206, name: '허보근').first_or_create(dong: 'B', ho: 206, name: '허보근', active: 1)
Resident.where(dong: 'B', ho: 207, name: '박기화').first_or_create(dong: 'B', ho: 207, name: '박기화', active: 1)
Resident.where(dong: 'B', ho: 208, name: '김동완').first_or_create(dong: 'B', ho: 208, name: '김동완', active: 1)
Resident.where(dong: 'B', ho: 209, name: '정남조').first_or_create(dong: 'B', ho: 209, name: '정남조', active: 1)

Resident.where(dong: 'C', ho: 101, name: '박성수').first_or_create(dong: 'C', ho: 101, name: '박성수', active: 1)
Resident.where(dong: 'C', ho: 102, name: '김동걸').first_or_create(dong: 'C', ho: 102, name: '김동걸', active: 1)
Resident.where(dong: 'C', ho: 103, name: '박육신').first_or_create(dong: 'C', ho: 103, name: '박육신', active: 1)
Resident.where(dong: 'C', ho: 104, name: '임소영').first_or_create(dong: 'C', ho: 104, name: '임소영', active: 1)
Resident.where(dong: 'C', ho: 105, name: '김서현(2)').first_or_create(dong: 'C', ho: 105, name: '김서현(2)', active: 1)
Resident.where(dong: 'C', ho: 106, name: '최성숙').first_or_create(dong: 'C', ho: 106, name: '최성숙', active: 1)
Resident.where(dong: 'C', ho: 107, name: '박삼희').first_or_create(dong: 'C', ho: 107, name: '박삼희', active: 1)
Resident.where(dong: 'C', ho: 108, name: '하상주').first_or_create(dong: 'C', ho: 108, name: '하상주', active: 1)
Resident.where(dong: 'C', ho: 201, name: '최명섭(2)').first_or_create(dong: 'C', ho: 201, name: '최명섭(2)', active: 1)
Resident.where(dong: 'C', ho: 202, name: '배미숙').first_or_create(dong: 'C', ho: 202, name: '배미숙', active: 1)
Resident.where(dong: 'C', ho: 203, name: '최성자').first_or_create(dong: 'C', ho: 203, name: '최성자', active: 1)
Resident.where(dong: 'C', ho: 204, name: '우경애(1.5)').first_or_create(dong: 'C', ho: 204, name: '우경애(1.5)', active: 1)
Resident.where(dong: 'C', ho: 205, name: '최정웅').first_or_create(dong: 'C', ho: 205, name: '최정웅', active: 1)
Resident.where(dong: 'C', ho: 206, name: '최병선').first_or_create(dong: 'C', ho: 206, name: '최병선', active: 1)
Resident.where(dong: 'C', ho: 207, name: '최금란').first_or_create(dong: 'C', ho: 207, name: '최금란', active: 1)

Resident.where(dong: 'D', ho: 101, name: '김남순').first_or_create(dong: 'D', ho: 101, name: '김남순', active: 1)
Resident.where(dong: 'D', ho: 102, name: '김유식').first_or_create(dong: 'D', ho: 102, name: '김유식', active: 1)
Resident.where(dong: 'D', ho: 103, name: '최병돌').first_or_create(dong: 'D', ho: 103, name: '최병돌', active: 1)
Resident.where(dong: 'D', ho: 104, name: '최병일(2)').first_or_create(dong: 'D', ho: 104, name: '최병일(2)', active: 1)
Resident.where(dong: 'D', ho: 105, name: '최병화(2)').first_or_create(dong: 'D', ho: 105, name: '최병화(2)', active: 1)
Resident.where(dong: 'D', ho: 106, name: '김영화(2)').first_or_create(dong: 'D', ho: 106, name: '김영화(2)', active: 1)
Resident.where(dong: 'D', ho: 201, name: '최창렬(2)').first_or_create(dong: 'D', ho: 201, name: '최창렬(2)', active: 1)
Resident.where(dong: 'D', ho: 202, name: '최수진').first_or_create(dong: 'D', ho: 202, name: '최수진', active: 1)
Resident.where(dong: 'D', ho: 203, name: '김종국(2)').first_or_create(dong: 'D', ho: 203, name: '김종국(2)', active: 1)
Resident.where(dong: 'D', ho: 204, name: '윤성일').first_or_create(dong: 'D', ho: 204, name: '윤성일', active: 1)
Resident.where(dong: 'D', ho: 205, name: '김종열(3)').first_or_create(dong: 'D', ho: 205, name: '김종열(3)', active: 1)

Resident.where(dong: 'E', ho: 101, name: '김미애(2.5)').first_or_create(dong: 'E', ho: 101, name: '김미애(2.5)', active: 1)
Resident.where(dong: 'E', ho: 102, name: '방정식(2.5)').first_or_create(dong: 'E', ho: 102, name: '방정식(2.5)', active: 1)
Resident.where(dong: 'E', ho: 103, name: '최상태').first_or_create(dong: 'E', ho: 103, name: '최상태', active: 1)
Resident.where(dong: 'E', ho: 104, name: '김형덕').first_or_create(dong: 'E', ho: 104, name: '김형덕', active: 1)
Resident.where(dong: 'E', ho: 105, name: '최문곤').first_or_create(dong: 'E', ho: 105, name: '최문곤', active: 1)
Resident.where(dong: 'E', ho: 106, name: '최부길').first_or_create(dong: 'E', ho: 106, name: '최부길', active: 1)
Resident.where(dong: 'E', ho: 201, name: '최상원').first_or_create(dong: 'E', ho: 201, name: '최상원', active: 1)
Resident.where(dong: 'E', ho: 202, name: '최경조').first_or_create(dong: 'E', ho: 202, name: '최경조', active: 1)
Resident.where(dong: 'E', ho: 203, name: '윤경리').first_or_create(dong: 'E', ho: 203, name: '윤경리', active: 1)
Resident.where(dong: 'E', ho: 204, name: '최규언').first_or_create(dong: 'E', ho: 204, name: '최규언', active: 1)
Resident.where(dong: 'E', ho: 205, name: '김춘자').first_or_create(dong: 'E', ho: 205, name: '김춘자', active: 1)
Resident.where(dong: 'E', ho: 206, name: '허만순').first_or_create(dong: 'E', ho: 206, name: '허만순', active: 1)
Resident.where(dong: 'E', ho: 207, name: '곽말순').first_or_create(dong: 'E', ho: 207, name: '곽말순', active: 1)
Resident.where(dong: 'E', ho: 208, name: '김영순(2)').first_or_create(dong: 'E', ho: 208, name: '김영순(2)', active: 1)

Resident.where(dong: 'F', ho: 101, name: '이하자').first_or_create(dong: 'F', ho: 101, name: '이하자', active: 1)
Resident.where(dong: 'F', ho: 102, name: '김구희(2)').first_or_create(dong: 'F', ho: 102, name: '김구희(2)', active: 1)
Resident.where(dong: 'F', ho: 103, name: '김동운(2)').first_or_create(dong: 'F', ho: 103, name: '김동운(2)', active: 1)
Resident.where(dong: 'F', ho: 104, name: '오국자').first_or_create(dong: 'F', ho: 104, name: '오국자', active: 1)
Resident.where(dong: 'F', ho: 105, name: '정동일(1.5)').first_or_create(dong: 'F', ho: 105, name: '정동일(1.5)', active: 1)
Resident.where(dong: 'F', ho: 106, name: '정상봉(1.5)').first_or_create(dong: 'F', ho: 106, name: '정상봉(1.5)', active: 1)
Resident.where(dong: 'F', ho: 201, name: '조성오(2)').first_or_create(dong: 'F', ho: 201, name: '조성오(2)', active: 1)
Resident.where(dong: 'F', ho: 202, name: '정제윤(2)').first_or_create(dong: 'F', ho: 202, name: '정제윤(2)', active: 1)
Resident.where(dong: 'F', ho: 203, name: '최봉섭(2)').first_or_create(dong: 'F', ho: 203, name: '최봉섭(2)', active: 1)
Resident.where(dong: 'F', ho: 204, name: '최지현').first_or_create(dong: 'F', ho: 204, name: '최지현', active: 1)
Resident.where(dong: 'F', ho: 205, name: '최낙훈').first_or_create(dong: 'F', ho: 205, name: '최낙훈', active: 1)
Resident.where(dong: 'F', ho: 206, name: '정윤선').first_or_create(dong: 'F', ho: 206, name: '정윤선', active: 1)

role_list = ['admin', 'user', 'member']
role_list.each do |role|
  Role.where(name: role).first_or_create
end

admin_user = User.create(email: 'admin@email.com', password: 'tlsrnd13!@')
admin_user.add_role :admin

